[11/03/2015 03:13:58 PM] - ERROR - status.py - MainThread - write - Traceback (most recent call last):

[11/03/2015 03:13:58 PM] - ERROR - status.py - MainThread - write -   File "/usr/bin/i3situation", line 9, in <module>

[11/03/2015 03:13:58 PM] - ERROR - status.py - MainThread - write -     
[11/03/2015 03:13:58 PM] - ERROR - status.py - MainThread - write - load_entry_point('i3situation==1.0.5', 'console_scripts', 'i3situation')()
[11/03/2015 03:13:58 PM] - ERROR - status.py - MainThread - write -   File "/usr/lib/python3.4/site-packages/i3situation/main.py", line 9, in main

[11/03/2015 03:13:58 PM] - ERROR - status.py - MainThread - write -     
[11/03/2015 03:13:58 PM] - ERROR - status.py - MainThread - write - s.run()
[11/03/2015 03:13:58 PM] - ERROR - status.py - MainThread - write -   File "/usr/lib/python3.4/site-packages/i3situation/core/status.py", line 127, in run

[11/03/2015 03:13:58 PM] - ERROR - status.py - MainThread - write -     
[11/03/2015 03:13:58 PM] - ERROR - status.py - MainThread - write - time.sleep(self.config.general['interval'])
[11/03/2015 03:13:58 PM] - ERROR - status.py - MainThread - write - KeyboardInterrupt
[11/03/2015 03:13:58 PM] - ERROR - status.py - MainThread - write - 
[11/03/2015 03:14:00 PM] - ERROR - status.py - MainThread - write - Exception ignored in: 
[11/03/2015 03:14:00 PM] - ERROR - status.py - MainThread - write - <module 'threading' from '/usr/lib/python3.4/threading.py'>
[11/03/2015 03:14:00 PM] - ERROR - status.py - MainThread - write - Traceback (most recent call last):

[11/03/2015 03:14:00 PM] - ERROR - status.py - MainThread - write -   File "/usr/lib/python3.4/threading.py", line 1294, in _shutdown

[11/03/2015 03:14:00 PM] - ERROR - status.py - MainThread - write -     
[11/03/2015 03:14:00 PM] - ERROR - status.py - MainThread - write - t.join()
[11/03/2015 03:14:00 PM] - ERROR - status.py - MainThread - write -   File "/usr/lib/python3.4/threading.py", line 1060, in join

[11/03/2015 03:14:00 PM] - ERROR - status.py - MainThread - write -     
[11/03/2015 03:14:00 PM] - ERROR - status.py - MainThread - write - self._wait_for_tstate_lock()
[11/03/2015 03:14:00 PM] - ERROR - status.py - MainThread - write -   File "/usr/lib/python3.4/threading.py", line 1076, in _wait_for_tstate_lock

[11/03/2015 03:14:00 PM] - ERROR - status.py - MainThread - write -     
[11/03/2015 03:14:00 PM] - ERROR - status.py - MainThread - write - elif lock.acquire(block, timeout):
[11/03/2015 03:14:00 PM] - ERROR - status.py - MainThread - write - KeyboardInterrupt
[11/03/2015 03:15:19 PM] - ERROR - status.py - MainThread - write - Traceback (most recent call last):

[11/03/2015 03:15:19 PM] - ERROR - status.py - MainThread - write -   File "/usr/bin/i3situation", line 9, in <module>

[11/03/2015 03:15:19 PM] - ERROR - status.py - MainThread - write -     
[11/03/2015 03:15:19 PM] - ERROR - status.py - MainThread - write - load_entry_point('i3situation==1.0.5', 'console_scripts', 'i3situation')()
[11/03/2015 03:15:19 PM] - ERROR - status.py - MainThread - write -   File "/usr/lib/python3.4/site-packages/i3situation/main.py", line 9, in main

[11/03/2015 03:15:19 PM] - ERROR - status.py - MainThread - write -     
[11/03/2015 03:15:19 PM] - ERROR - status.py - MainThread - write - s.run()
[11/03/2015 03:15:19 PM] - ERROR - status.py - MainThread - write -   File "/usr/lib/python3.4/site-packages/i3situation/core/status.py", line 127, in run

[11/03/2015 03:15:19 PM] - ERROR - status.py - MainThread - write -     
[11/03/2015 03:15:19 PM] - ERROR - status.py - MainThread - write - time.sleep(self.config.general['interval'])
[11/03/2015 03:15:19 PM] - ERROR - status.py - MainThread - write - KeyboardInterrupt
[11/03/2015 03:15:19 PM] - ERROR - status.py - MainThread - write - 
[11/03/2015 03:15:20 PM] - ERROR - status.py - MainThread - write - Exception ignored in: 
[11/03/2015 03:15:20 PM] - ERROR - status.py - MainThread - write - <module 'threading' from '/usr/lib/python3.4/threading.py'>
[11/03/2015 03:15:20 PM] - ERROR - status.py - MainThread - write - Traceback (most recent call last):

[11/03/2015 03:15:20 PM] - ERROR - status.py - MainThread - write -   File "/usr/lib/python3.4/threading.py", line 1294, in _shutdown

[11/03/2015 03:15:20 PM] - ERROR - status.py - MainThread - write -     
[11/03/2015 03:15:20 PM] - ERROR - status.py - MainThread - write - t.join()
[11/03/2015 03:15:20 PM] - ERROR - status.py - MainThread - write -   File "/usr/lib/python3.4/threading.py", line 1060, in join

[11/03/2015 03:15:20 PM] - ERROR - status.py - MainThread - write -     
[11/03/2015 03:15:20 PM] - ERROR - status.py - MainThread - write - self._wait_for_tstate_lock()
[11/03/2015 03:15:20 PM] - ERROR - status.py - MainThread - write -   File "/usr/lib/python3.4/threading.py", line 1076, in _wait_for_tstate_lock

[11/03/2015 03:15:20 PM] - ERROR - status.py - MainThread - write -     
[11/03/2015 03:15:20 PM] - ERROR - status.py - MainThread - write - elif lock.acquire(block, timeout):
[11/03/2015 03:15:20 PM] - ERROR - status.py - MainThread - write - KeyboardInterrupt
